### ISSUE TITLE
Item creation failures

### ISSUE THREAD

**Issue by pjhartzell** [stactools-packages/goes-glm#17]
Seeing some item creation failures. I randomly sampled the Planetary Computer's holdings for 1000 NetCDFs and cataloged the error tracebacks in the attached file: [log_summary.txt](https://github.com/stactools-packages/goes-glm/files/9482445/log_summary.txt)

It looks like there are some inconsistencies in the NetCDF content in up to 10% of the sampled files. I've bundled the example NetCDF files listed in the log_summary in the attached zip file: [example_files.zip](https://github.com/stactools-packages/goes-glm/files/9482431/example_files.zip). The NetCDF files are also [publicly available](https://microsoft.github.io/AIforEarthDataSets/data/goes-r.html).

**Comment by m-mohr** [comment]
Thank you for the report. I'm very sorry about the issues, which did not appear in the limited set of examples that I has access to. I've now included all the examples files in the test suite and commited a bug fix. Please see below what the (temporary) solutions look like. We should contact NOAA for clarification. Would you do that or shall I?

> KeyError: 'flash_frame_time_offset_of_first_event'

Sometimes it seems the frame times are missing. I'll leave them out of the geoparquet now if they are missing. Still, we should ask NOAA whether that is intentional.

> IndexError: index exceeds dimension bounds

This means for some variables that reported count (e.g. in event_count) is not reflecting the number of rows in the variables (e.g. event_id). For now, I'm using the count value by default but if it doesn't match I'm falling back to the number of rows that are actually available and raise a warning. Still, we should ask NOAA whether this is intentional and what we should do in such a case.

> TypeError: unsupported type for timedelta seconds component: NoneType

It seems for some time offsets a None/NaN/null value is reported. For now, I'm simply writing "null" to the geoparquet file, too. I'm also adding a short description to the column so that users are aware. Still, we should ask NOAA whether that is intentional and/or has any implications.

> KeyError: 'GOES_Test'

Some files report GEOS_TEST instead of GOES_West/East. I'm now falling back to derive that from the platform number if possible. Otherwise, I throw an error because it would be ambiguous.

> TypeError: only integer scalar arrays can be converted to a scalar index

This happends when no events/flashed occured in the timeframe. For an unknown reason I'm getting "--" instead of 0 then from the upstream library. Have you seen that before? For now, I'm issuing a warning and assume 0 in the code.

**Comment by m-mohr** [comment]
Shall I re-release or do we wait for the NOAA feedback?

**Comment by gadomski** [comment]
Let's wait until we get fixes for all the above issues, then release. If @pjhartzell needs to use this package with only some of the fixes, he can pin to a commit.

**Comment by pjhartzell** [comment]
@gadomski found some docs relating to the first error: **KeyError: 'flash_frame_time_offset_of_first_event'**. Evidently there was a version change (the version is not indicated anywhere) that added the three variables containing `..._frame_time_offset_...` in their names. Older files will have 45 variables; newer files will have 48.

- doc href: https://www.noaasis.noaa.gov/pdf/ps-pvr/goes-16/GLM/Full/GOES16_GLM_FullValidation_ProductPerformanceGuide.pdf
- relevant snippet from page 15 of the doc:
```
How to Determine If Data is DO.07.00.00 or a Prior Version: There are no external indications 
in the file that the format has changed. One way to determine which version of the file you are 
working with is to count the number of variables in the file. If it is 45, it is the OLD format, will not 
have the SUVs (but will still have the “_Unsigned” designation for the non-standard unsigned 
integers). If the variable count is 48, it is the DO.07.00.00 version of the file and will have the list 
of SUVs (above) along with the “_Unsigned” designation for the non-standard unsigned integers.
```
The table above this snippet in the doc lists the names of the variable that were added in version DO.07.00.00.

[`parquet.py`](https://github.com/stactools-packages/goes-glm/blob/8d617a905a5963e033c7648fee86b01d12fa3f32/src/stactools/goes_glm/parquet.py#L174) handles the issue. But not sure if you want to change the way it is handled or update the logger warning now that we have some docs on what is going on.

**Comment by m-mohr** [comment]
Thanks a lot, yeah I will make a small change and make the tests a bit more precise!

**Comment by m-mohr** [comment]
I've just made the changes. Any news from NOAA regarding the other points?

**Comment by m-mohr** [comment]
I've just made the changes. Any news from NOAA regarding the other points? @gadomski

**Comment by pjhartzell** [comment]
Also in the doc that @gadomski found are warnings about missing `_Unsigned` attributes on some variables. This is the cause of the **TypeError: unsupported type for timedelta seconds component: NoneType** errors. There are unsigned integer bytes being incorrectly read as signed integers.

We might need to check each variable that is supposed to have an `_Unsigned` attribute to verify it exists. If it doesn't, some modifications are necessary to obtain the correct values. Here's a [gist with a notebook](https://gist.github.com/pjhartzell/23d1c679e58fffb297088e9fc3e5fe01) that provides a link to a table that lists which variables should have an `_Unsigned` attribute and two approaches that I've found to correctly read the variable values when the `_Unsigned` attribute is missing.

**Comment by pjhartzell** [comment]
I haven't found anything for the **IndexError: index exceeds dimension bounds** error. I think your method of overriding the provided `count` with the actual count when they disagree is good for now.

**Comment by m-mohr** [comment]
Ah... interesting. I checked the values with Panoply and assumed that what I get out there is actually correct and based my fix on this, which it seems it is not because the file is effectively defect due to the missing unsigned indicator. I'll look into this. I'm wondering whether it should be our responsibility to fix defect files? Users of the GRIB2 files that read it with "normal software" like Panoply will also get nan values and as such may get different results based on whether they use the geoparquet or GRIB2 files. That's somehow weird. (I assume normal users would not read these guide books / PDFs from NOAA.)

**Comment by pjhartzell** [comment]
>I assume normal users would not read these guide books / PDFs from NOAA.

Yeah, I agree that this is a hidden bug and most users will struggle to find it and fix it. @gadomski, your thoughts on repairing the netCDF files? I hate to modify source files, but it definitely creates a disconnect between the corrected data in the parquet files and the defective source file.

**Comment by m-mohr** [comment]
In principle, we could simply provide an option for this. See #18 for details.

**Comment by m-mohr** [comment]
So going through the issues again, I think we were able to solve them somewhat and there are two that could be sent to NOAA for clarification.

- [x] KeyError: 'flash_frame_time_offset_of_first_event'
- [x] IndexError: index exceeds dimension bounds - this is something we could still ask NOAA about.
- [x] TypeError: unsupported type for timedelta seconds component: NoneType
- [x] KeyError: 'GOES_Test' - it is still open whether another bounding box should be used, but on the other hand the bboxes for the other data is also not very precise and NOAA wasn't able to provide anything better yet.
- [x] TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by pjhartzell** [comment]
Agreed that we can still follow up with NOAA about the index exceeding dimension bounds.

Some thoughts on the "GOES_Test" `orbital_slot` and use of bbox for geometry: 

1. The values in the `lat_field_of_view_bounds` and `lon_field_of_view_bounds` variables for the GOES_Test data are constant:
```
lat = [ 66.56 -66.56]
lon = [-156.06  -22.94]
```

And since we are using the bbox for the geometry, I think we have what we need to produce Items for GOES_Test data.

2. I also looked in the data holdings and no netCDF files exist for the drift time periods noted and handled in the code. There is no GOES-16 data in 2017 and there is a gap in the GOES-17 data from October 25, 2018 to November 12, 2018 (inclusive). So that logic could be removed.

**Comment by m-mohr** [comment]
Thanks for verifying with the data holding that the fallback code is not needed. I removed it again.

So this issue is basically finished except that we could still ask NOAA about the remaining questions, right?

**Comment by pjhartzell** [comment]
>we could still ask NOAA about the remaining questions, right?

I believe the only remaining question is the "IndexError: index exceeds dimension bounds" question. I'll tag @gadomski on whether that's worth following up with NOAA.

**Comment by pjhartzell** [comment]
I opened a PR with some edits on how I think the Test orbital slot should be handled. Let me know your thoughts.

**Comment by m-mohr** [comment]
Opened a new issue for the issue that reported counts are not reflecting the number of rows in the variables: #22 
So now we can close this issue which got a bit hard to follow.
